## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/taco
spring.datasource.username=postgres
spring.datasource.password=pass
#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
